#!/bin/bash
# depwire-security.sh
# Security scanning and remediation workflow
# Usage: ./depwire-security.sh [target-path] [fail-on-severity]

set -e

TARGET="${1:-}"
FAIL_ON="${2:-high}"

echo "=== Depwire Security Audit ==="
echo "Target: ${TARGET:-full scan}"
echo "Fail on: $FAIL_ON+ severity"
echo ""

echo "Step 1: Running security scan..."
echo "Command: security_scan(target=\"${TARGET:-full scan}\", graphAware=true)"
echo ""
echo "Graph-aware severity:"
echo "  CRITICAL: Reachable from MCP tools or HTTP routes (remote exploit)"
echo "  HIGH:     Reachable from internal services"
echo "  MEDIUM:   Not directly reachable but vulnerable"
echo "  LOW:      Theoretical vulnerability"
echo ""

echo "Step 2: Triage findings by severity"
echo "===================================="
echo ""
echo "CRITICAL (fix immediately):"
echo "  1. impact_analysis(symbol)"
echo "  2. Understand attack vector"
echo "  3. Fix in same session"
echo "  4. verify_change before commit"
echo ""
echo "HIGH (fix within sprint):"
echo "  1. Document attack scenario"
echo "  2. Schedule fix"
echo "  3. Use verify_change before commit"
echo ""
echo "MEDIUM (next sprint):"
echo "  1. Add to tech debt backlog"
echo "  2. Document risk"
echo ""
echo "LOW (backlog):"
echo "  1. Document for future cleanup"
echo ""
echo ""

echo "Step 3: Fix patterns"
echo "===================="
echo ""
echo "Shell injection fix:"
echo "  Before: exec(\`ls \${userInput}\`)"
echo "  After:  execFile('ls', [userInput])"
echo ""
echo "Hardcoded secrets fix:"
echo "  Before: const key = 'sk-1234567890';"
echo "  After:  const key = process.env.API_KEY;"
echo ""
echo "Path traversal fix:"
echo "  Before: readFile(path.join(base, userInput))"
echo "  After:  normalize + startsWith check"
echo ""
echo "XSS fix:"
echo "  Before: element.innerHTML = userInput"
echo "  After:  element.textContent = userInput"
echo ""

echo "Step 4: CI Integration"
echo "======================="
echo ""
echo "Fail pipeline on critical/high:"
echo "  depwire security --fail-on=high"
echo ""
echo "JSON output for automation:"
echo "  depwire security --json > security-report.json"
echo ""
echo "GitHub Action example:"
echo "  - name: Security scan"
echo "    run: depwire security --fail-on=high"
echo ""

echo "Step 5: Pre-PR gate"
echo "==================="
echo ""
echo "Required checks before merge:"
echo "  1. security_scan → 0 critical"
echo "  2. security_scan → 0 high (if fail-on=critical)"
echo "  3. verify_change → 0 issues"
echo ""

echo "=== Common Vulnerability Patterns ==="
echo ""
echo "Dependency CVEs:"
echo "  npm audit"
echo "  npm update <package>@latest"
echo ""
echo "Shell injection:"
echo "  Never: exec(\`cmd \$var\`)"
echo "  Always: execFile('cmd', [var]) with validation"
echo ""
echo "Secrets:"
echo "  Never: hardcoded API keys, tokens, passwords"
echo "  Always: environment variables, secrets managers"
echo ""
echo "SQL/NoSQL injection:"
echo "  Never: \`SELECT * FROM users WHERE id = \${id}\`"
echo "  Always: parameterized queries"
echo ""

echo "=== False Positive Handling ==="
echo ""
echo "Security scan can have false positives on:"
echo "  - Dynamic imports (runtime loading)"
echo "  - Reflection usage (meta-programming)"
echo "  - Framework magic (DI containers)"
echo "  - Test-only code"
echo ""
echo "To verify a finding:"
echo "  1. get_dependents(symbol)"
echo "  2. get_file_context(filePath)"
echo "  3. If truly vulnerable → fix"
echo "  4. If false positive → document reason"