#!/bin/bash
# depwire-dead-code.sh
# Dead code detection and cleanup workflow
# Usage: ./depwire-dead-code.sh [min-confidence]

set -e

MIN_CONFIDENCE="${1:-high}"

echo "=== Depwire Dead Code Cleanup ==="
echo "Minimum confidence: $MIN_CONFIDENCE"
echo ""

echo "Step 1: Finding dead code..."
echo "Command: find_dead_code(confidence=\"$MIN_CONFIDENCE\")"
echo ""

echo "=== Confidence Levels ==="
echo ""
echo "HIGH:   Definitely unused — safe to auto-remove"
echo "MEDIUM: Likely unused — verify with get_dependents"
echo "LOW:    Possibly unused — manual review required"
echo ""
echo "NEVER auto-delete MEDIUM/LOW — edge cases exist"
echo "  (dynamic imports, reflection, framework magic)"
echo ""

echo "Step 2: Verification workflow for each symbol"
echo "============================================="
echo ""
echo "For HIGH confidence:"
echo "  1. search_symbols(query=\"SymbolName\")"
echo "  2. get_dependents(symbol=\"SymbolName\")"
echo "  3. If no dependents → safe to remove"
echo "  4. If only test files → safe to remove"
echo ""
echo "For MEDIUM/LOW:"
echo "  1. get_dependents(symbol=\"SymbolName\")"
echo "  2. get_file_context(filePath=\"path/to/file\")"
echo "  3. Flag for human review"
echo "  4. Manual delete after review"
echo ""

echo "Step 3: Safe deletion workflow"
echo "==============================="
echo ""
echo "Before deleting any symbol:"
echo ""
echo "  1. simulate_change(operation=\"delete\", target=\"path/to/symbol\")"
echo "  2. Review broken_imports (must be 0)"
echo "  3. Review affected_nodes"
echo "  4. If clean → proceed with deletion"
echo "  5. If not clean → investigate further"
echo ""

echo "Step 4: Post-cleanup verification"
echo "=================================="
echo ""
echo "After removal:"
echo "  1. verify_change(...) → 0 broken imports"
echo "  2. get_health_score → verify no regression"
echo "  3. build → must pass"
echo ""

echo "=== Quick Reference ==="
echo ""
echo "depwire dead-code --min-confidence=high"
echo ""
echo "Categories of dead code:"
echo "  - Unused exports (exported but never imported)"
echo "  - Unused internal symbols (defined but never called)"
echo "  - Duplicate implementations (功能重复)"
echo "  - Refactored code (old implementation not removed)"
echo "  - Experimental code (features flag disabled)"
echo ""
echo "Common causes:"
echo "  - Feature flags removed but code kept"
echo "  - Refactors that left behind helpers"
echo "  - Copy-paste code that was adapted but originals kept"
echo "  - Migration artifacts (e.g., old API clients)"
echo ""
echo "For full automated cleanup, integrate into CI pipeline:"